### ISSUE TITLE
@Input/@Output names

### ISSUE THREAD

**Issue by pegak** [flowup/knowledge#20]
# Motivation

It's better to be sure that we don't have a different name for input/output when sending and when using in a component. Also, this should ensure that there won't be a conflict with any native event.

# Proposal

```
"no-input-rename": true,
"no-output-native": true,
"no-output-on-prefix": true,
"no-output-rename": true
```
----

# Impact

I haven't found any occurrence of this in Camvision/Veronica Inside/ConsuMD, but I think, it's better to have those rules active, because **better safe, than sorry.**

----

# Links and References

https://medium.com/@samichkhachkhi/dont-prefix-angular-output-properties-with-on-e5a638517613
http://codelyzer.com/rules/no-input-rename/
http://codelyzer.com/rules/no-output-rename/
http://codelyzer.com/rules/no-output-native/
http://codelyzer.com/rules/no-output-on-prefix/

**Comment by matejchalk** [comment]
I think even in some case where you have a good reason for renaming an Input/Output, having to add a `tslint:disable` helps to highlight it.
