### ISSUE TITLE
Force alt attributes for images

### ISSUE THREAD

**Issue by pegak** [flowup/knowledge#31]
# Motivation

It's not semantic and accessible if you aren't using alt attribute for image. That leads to worse usability, SEO, searchability etc.

# Proposal

Add http://codelyzer.com/rules/template-accessibility-alt-text/ rule to our codebase.

----

**Comment by vmasek** [comment]
Prepare a directive/component for icons

**Comment by vmasek** [comment]
This CSS 😄 
https://pbs.twimg.com/media/EPwSrq1UwAAN6U1?format=jpg&name=4096x4096

or 

https://naughty-no-alt.glitch.me/
