### ISSUE TITLE
Prefer On Push change detection

### ISSUE THREAD

**Issue by pegak** [flowup/knowledge#35]
# Motivation

We try to use On Push change detection everywhere, when don't it has reason so it would be better to have it checked and have to add comment why it's not used here.

# Proposal

Implement http://codelyzer.com/rules/prefer-on-push-component-change-detection/ in our codebase.

----

# Impact

Comment should be added to disable this rule and with that also comment why it was turned off.

## Pros

Better codebase

## Cons

Legacy projects might not use this all the time.

**Comment by vmasek** [comment]
Leaving this open for examples why is `OnPush` strategy harmfull
