### ISSUE TITLE
Check unused CSS

### ISSUE THREAD

**Issue by pegak** [flowup/knowledge#36]
# Motivation

Sometimes we have "dead code" in our CSS and it can be checked.

# Proposal

Implement http://codelyzer.com/rules/no-unused-css/ rule to our codebase.

----

# Impact

Elimination of dead code in CSS.

## Pros

Smaller and cleaner code

**Comment by vmasek** [comment]
This rule does not work, it supports only the CSS and it is still rough.

**Comment by pegak** [comment]
Ok!
