### ISSUE TITLE
Use trackBy

### ISSUE THREAD

**Issue by pegak** [flowup/knowledge#37]
# Motivation

Usage of trackBy function leads to better performance and thinking about what we iterate through.

# Proposal

Implement http://codelyzer.com/rules/template-use-track-by-function/ rule in our codebase.

----

# Impact

## Pros

Performance
Knowledge about data

## Cons

Adding a lot of trackBy functions (although they are pretty simple)

----

# Links and References

https://medium.com/better-programming/improving-angular-ngfor-performance-through-trackby-ae4cf943b878

**Comment by vmasek** [comment]
I agree but I don't really know how would we auto check that. 
Maybe adding this to some "review checklist" to catch that manually?

**Comment by pegak** [comment]
What would you like to auto check? That's what rule will do, right?

I am for having it on all ngFors.

**Comment by vmasek** [comment]
Yes, that was my point is it beneficial to have it on all of the `ngFor`s?

**Comment by pegak** [comment]
We should implement better approach without changing a lot of code, as we discussed, there's possibility to have custom ngFor which extends current one.
