### ISSUE TITLE
Don't force typedefs for arrow functions

### ISSUE THREAD

**Issue by matejchalk** [flowup/knowledge#42]
# Proposal

Recently, [the `"arrow-call-signature"` option was added to the TSLint `"typedef"` rule](https://github.com/flowup/knowledge/issues/38). This proposal is to revert that change.

# Motivation

Forcing type definitions for arrow functions is too strict, since these are often one-liners where the return type is easily inferred by Typescript. Requiring return type annotation would create unnecessary overhead.

**Comment by vmasek** [comment]
I also encountered a problem where you need to "ignore" this rule for all of your dynamic import in project's routing.

**Comment by vmasek** [comment]
For other cases like Array operations or RxJS operators, it seems like a little too much and doesn't bring the value.

**Comment by PeterSisovsky** [comment]
We tried this rule on our project and we did not see any added value, contrariwise this was causing us problems, so we turned this rule off.

**Comment by estankovic** [comment]
I Agree, this rule is not useful for all projects. Might cause unnecessary overhead and be counterproductive.
